/** @type {import('tailwindcss').Config} */
const colors = require("tailwindcss/colors");
module.exports = {
  content: [
    "src/**/**/**/**/*.{html,js,jsx,tsx,ts}",
    "common/components/**/*.{html,js,jsx,tsx,ts}",
    "src/app/**/**/**/*.{js,ts,jsx,tsx}", // <-- Add this line
  ],
  darkMode: "class",
  theme: {
    extend: {
    },
    zIndex: {
      10: "10",
      20: "20",
      30: "30",
      40: "40",
      50: "50",
      60: "60",
      70: "70",
      80: "80",
      90: "90",
      98: "98",
      99: "99",
      100: "100",
      101: "101",
      102: "102",
      999: "999",
      1000: "1000",
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",
      black: "#000",
      white: "#fff",
      gray: colors.gray,
      slate: colors.slate,
      neutral: colors.neutral,
      zinc: colors.zinc,
      stone: colors.stone,
      red: colors.red,
      orange: colors.orange,
      amber: colors.amber,
      yellow: colors.yellow,
      lime: colors.lime,
      green: colors.green,
      emerald: colors.emerald,
      teal: colors.teal,
      cyan: colors.cyan,
      sky: colors.sky,
      blue: colors.blue,
      indigo: colors.indigo,
      violet: colors.violet,
      purple: colors.purple,
      fuchsia: colors.fuchsia,
      pink: colors.pink,
      rose: colors.rose,
      dark: colors.gray,
      primary: colors.lime,
      secondary: colors.purple,
    },
  },
  plugins: [],
};
